name: Microsoft Teams Deploy Card
author: Project Toko Bifrost
description: Notify your Teams channel with a beautiful, comprehensive deployment card
branding:
  icon: bell
  color: purple

inputs:
  webhook-uri:
    description: Microsoft Teams webhook URI
    required: true
  github-token:
    description: Github token
    required: true
  environment:
    description: Name of the environment (won't be included in the card if none)
    required: false
    default: null
  timezone:
    description: Timezone for notification
    required: false
    default: UTC
  card-layout-start:
    description: Card layout on start (i.e. "complete", "cozy", "compact")
    required: false
    default: complete
  card-layout-exit:
    description: Card layout on end (i.e. "complete", "cozy", "compact")
    required: false
    default: compact
  show-on-start:
    description: Show the MS Teams card upon starting this Github Actions job
    required: false
    default: true
  show-on-exit:
    description: Show the MS Teams card upon exiting this Github Actions job
    required: false
    default: true
  show-on-failure:
    description: Show the MS Teams card upon failure only of this Github Actions job
    required: false
    default: false
  custom-facts:
    description: YAML-parseable multiline string defining the list of object with name and value to display on the facts table
    required: false
    default: null
  enable-view-status-action:
    description: Enable an action to view the deployment status
    required: false
    default: true
  enable-review-diffs-action:
    description: Enable an action to review commit diffs
    required: false
    default: true
  view-status-action-text:
    description: Customize action text in viewing the deployment status
    required: false
    default: View build/deploy status
  review-diffs-action-text:
    description: Customize action text in reviewing commit diffs
    required: false
    default: Review commit diffs
  custom-actions:
    description: Add more actions and links on cozy and complete layout
    required: false
    default: null
  include-files:
    description: Only for complete layout; Set false to exclude list of files
    required: false
    default: true
  allowed-file-len:
    description: Allowed number of files to display
    required: false
    default: 7

runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
